### ISSUE TITLE
Python Local fails to Run

### ISSUE THREAD

**Issue by avagdumortesin** [TikaelSol/PF2e-Foundry-Data-Entry#10]
Following the steps in `README.md`, I downloaded the repo onto my computer. I am using an Apple Silicon (M1) Mac running macOS Monterey (12.4), with Python 3.8.9 installed.

I navigated to the folder where I downloaded the repo, and used PIP to install Regex and Pyperclip per the `requirements.txt`, then attempted to run `dataEntry.py`, and received a traceback that `constants.py` could not be imported. To fix this, I modified `dataEntry.py` with the following:
```
import sys
sys.path.insert(0, '~/Developer/Foundry/PF2/PF2e-Foundry-Data-Entry/pf2e_data')
```

This allowed the script to run, but it never presented any sort of dialog to enter data to. When I finally decided to cancel the script, I received the following traceback:
```
PF2e-Foundry-Data-Entry % python3 dataEntry.py
^CTraceback (most recent call last):
  File "dataEntry.py", line 372, in <module>
    main()
  File "dataEntry.py", line 367, in main
    reformat(input(), third_party = False, companion = False, eidolon = False, ancestry = False, use_clipboard=True, add_gm_text = False, inline_rolls = True, add_conditions = True, add_inline_checks = True, add_inline_templates = True, remove_non_ASCII = True)
KeyboardInterrupt
```

As I was writing this, I realized that there is another `dataEntry.py` in the `pf2e_data` folder; when I attempted to use this one, I experienced similar behavior with a different traceback:
```
PF2e-Foundry-Data-Entry % cd pf2e_data 
pf2e_data % python3 dataEntry.py
^CTraceback (most recent call last):
  File "dataEntry.py", line 246, in <module>
    main()
  File "dataEntry.py", line 242, in main
    reformat(input(), use_clipboard=True)
KeyboardInterrupt
```

Any suggestions on how to get this to function would be appreciated!

**Comment by TikaelSol** [comment]
It's possible that the last version is bugged, I have kind of a hacky approach to making the standalone app as you can see with the commented out code. I'll take a look, I definitely shouldn't have two copies of the python script anyways.

**Comment by avagdumortesin** [comment]
Looks like the update fixed this, as I'm now able to get the local install to run.
