### ISSUE TITLE
Local Install Adds Unexpected Line Breaks

### ISSUE THREAD

**Issue by avagdumortesin** [TikaelSol/PF2e-Foundry-Data-Entry#12]
When copying text from a rulebook, and using the Local Install version, the output still contains the line breaks from the rulebook.

As an example, open the Core Rulebook (version 3) and go to the Request action on page 247. Selecting the text appears like this:
<img width="351" alt="Screen Shot 2022-07-08 at 3 04 16 PM" src="https://user-images.githubusercontent.com/55938242/178076126-793ee96f-85a4-45c7-bcc8-21f182d11ff9.png">

After running through the Local Install, the text output shows as:
<img width="570" alt="Screen Shot 2022-07-08 at 3 01 44 PM" src="https://user-images.githubusercontent.com/55938242/178076206-fc862279-9be5-4cd0-b05e-4c711a7cae1f.png">

The same text appears more correctly when using the Jupyter Notebook, with the exception that it doesn't include the breaks for the success ratings:
<img width="743" alt="Screen Shot 2022-07-08 at 3 08 27 PM" src="https://user-images.githubusercontent.com/55938242/178076369-8f49cdb4-d6c8-4421-ad0a-3299faa9ee94.png">

**Comment by avagdumortesin** [comment]
With some further testing, I was able to determine that the script acts as expected when following this path:

1. Copy text from PDF (Acrobat Pro)
2. Paste text into a text editor (BBEdit, in my case)
3. Copy text from the text editor
4. Paste text into the GUI for the script

When not copying directly from the PDF into the GUI is when I experience the behavior; is this expected?

**Comment by TikaelSol** [comment]
This sounds like something with additional formatting coming along with the copied data. I can't reproduce the issue at all, but I don't use Adobe so maybe it's that. You can try pasting without formatting (control-shift-v on Windows or command-option-shift-v on Mac OS).

**Comment by avagdumortesin** [comment]
Ah, definitely appears to be something that Adobe's doing; opening the PDF in Preview (macOS PDF/image viewer app) works as expected.
