### ISSUE TITLE
Society Check returning as a header

### ISSUE THREAD

**Issue by KLSteinwand** [TikaelSol/PF2e-Foundry-Data-Entry#13]
When reformating a Society Skill Check, it turns it in a header line.

Example:

A PC succeeding at a DC 20 Religion or DC 20 Society check to Recall Knowledge recognizes the patterns painted on the hut as symbols of strength, virility, and skill in battle, but they’re not associated with any established faith.

returns as

`<p>A PC succeeding at a @Check[type:religion|dc:20] or DC 20</p><h2>Society</h2><p>check to Recall Knowledge recognizes the patterns painted on the hut as symbols of strength, virility, and skill in battle, but they're not associated with any established faith.</p>`

**Comment by TikaelSol** [comment]
You have the "Handle Ancestry Description Text" option set. That's for sussing out the society header in there. This is what I get from running it without that option on
`<p>A PC succeeding at a @Check[type:religion|dc:20] or @Check[type:society|dc:20] check to Recall Knowledge recognizes the patterns painted on the hut as symbols of strength, virility, and skill in battle, but they're not associated with any established faith.</p>`
