### ISSUE TITLE
Formatter Escaping Quotation Marks in span class

### ISSUE THREAD

**Issue by Arnatious** [TikaelSol/PF2e-Foundry-Data-Entry#14]
On version 2.12 (2a7a5e1)

![image](https://github.com/TikaelSol/PF2e-Foundry-Data-Entry/assets/874519/65afd7e8-0810-4a89-b803-c8c312bd510e)

The escaped quotation marks cause the class to be ill formed when copying into foundry.

**Comment by TikaelSol** [comment]
Fixed in 2.13
